version: '3'

services:
  freeswitch:
    build:
      dockerfile: freeswitch/Dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    volumes:
      - ./freeswitch/conf/freeswitch.xml:/usr/local/freeswitch/conf/freeswitch.xml
      - ./freeswitch/scripts:/home/${USER_NAME}/scripts
      - ./scripts:/tmp/scripts
      - ~/.gitconfig:/home/${USER_NAME}/.gitconfig
    cap_add:
      - SYS_NICE
    command: sudo -E /usr/local/freeswitch/bin/freeswitch -nc -nf -nonat

  tester:
    build:
      dockerfile: tester/Dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    volumes:
      - ../:/home/${USER_NAME}/src/
      - ./scripts:/tmp/scripts
      - ./tmuxinator/dev.yml:/home/${USER_NAME}/.config/tmuxinator/dev.yml
      - ./tester/mrcp_server_default.js:/home/${USER_NAME}/src/mrcp_server/config/default.js
      - ~/.gitconfig:/home/${USER_NAME}/.gitconfig
    command: tail -f /dev/null

